language: node_js
node_js:
  - '8'
before_install:
  - node -v
  - npm -v
install:
  - npm install
script:
  - npm test
  - npm run lint
  - npm run build
# deploy:
#   provider: surge
#   skip_cleanup: true
#   project: ./dist/
#   domain: https://clipps.surge.sh
#   on:
#     branch: master
