// flow-typed signature: 41950ad81c8d803e11381335669e0557
// flow-typed version: <<STUB>>/md5.js_v^1.3.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'md5.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'md5.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'md5.js/index' {
  declare module.exports: $Exports<'md5.js'>;
}
declare module 'md5.js/index.js' {
  declare module.exports: $Exports<'md5.js'>;
}
